/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { CaseTask } from '../Models/CaseTaskModel';

export class CaseTaskService {
  private static readonly dataSourceName = 'casetask';

  public static async create(record: Omit<CaseTask, 'TaskId'>): Promise<IOperationResult<CaseTask>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<CaseTask, 'TaskId'>, CaseTask>(
      CaseTaskService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<CaseTask, 'TaskId'>>): Promise<IOperationResult<CaseTask>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<CaseTask, 'TaskId'>>, CaseTask>(
      CaseTaskService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(CaseTaskService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<CaseTask>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<CaseTask>(
      CaseTaskService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<CaseTask[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<CaseTask>(
      CaseTaskService.dataSourceName,
      options
    );
    return result;
  }
}
