/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { CaseNote } from '../Models/CaseNoteModel';

export class CaseNoteService {
  private static readonly dataSourceName = 'casenote';

  public static async create(record: Omit<CaseNote, 'NoteId'>): Promise<IOperationResult<CaseNote>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<CaseNote, 'NoteId'>, CaseNote>(
      CaseNoteService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<CaseNote, 'NoteId'>>): Promise<IOperationResult<CaseNote>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<CaseNote, 'NoteId'>>, CaseNote>(
      CaseNoteService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(CaseNoteService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<CaseNote>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<CaseNote>(
      CaseNoteService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<CaseNote[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<CaseNote>(
      CaseNoteService.dataSourceName,
      options
    );
    return result;
  }
}
