/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { GetActiveCasesResponse } from '../Models/GetActiveCasesModel';

export class GetActiveCasesService {
  private static readonly dataSourceName = 'lrdigs';

  public static async GetActiveCases(): Promise<IOperationResult<GetActiveCasesResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.executeAsync<void, GetActiveCasesResponse>({
      connectorOperation: {
        tableName: GetActiveCasesService.dataSourceName,
        operationName: 'GetActiveCases',
      },
    });
    return result;
  }
}
