/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { usp_UpdateCaseStatusResponse } from '../Models/usp_UpdateCaseStatusModel';

export class usp_UpdateCaseStatusService {
  private static readonly dataSourceName = 'lrdigs';

  public static async usp_UpdateCaseStatus(ChangedBy?: string, NewStatus?: string, SystemCaseId?: string): Promise<IOperationResult<usp_UpdateCaseStatusResponse>> {
    const parameters: { ChangedBy?: string, NewStatus?: string, SystemCaseId?: string } = { ChangedBy, NewStatus, SystemCaseId };
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.executeAsync<{ ChangedBy?: string, NewStatus?: string, SystemCaseId?: string }, usp_UpdateCaseStatusResponse>({
      connectorOperation: {
        tableName: usp_UpdateCaseStatusService.dataSourceName,
        operationName: 'usp_UpdateCaseStatus',
        parameters
      },
    });
    return result;
  }
}
