/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { usp_CreateCaseResponse } from '../Models/usp_CreateCaseModel';

export class usp_CreateCaseService {
  private static readonly dataSourceName = 'lrdigs';

  public static async usp_CreateCase(): Promise<IOperationResult<usp_CreateCaseResponse>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.executeAsync<void, usp_CreateCaseResponse>({
      connectorOperation: {
        tableName: usp_CreateCaseService.dataSourceName,
        operationName: 'usp_CreateCase',
      },
    });
    return result;
  }
}
