/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { vw_ActiveCases } from '../Models/vw_ActiveCasesModel';

export class vw_ActiveCasesService {
  private static readonly dataSourceName = 'vw_activecases';

  public static async create(record: vw_ActiveCases): Promise<IOperationResult<vw_ActiveCases>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<vw_ActiveCases, vw_ActiveCases>(
      vw_ActiveCasesService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: vw_ActiveCases): Promise<IOperationResult<vw_ActiveCases>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<vw_ActiveCases, vw_ActiveCases>(
      vw_ActiveCasesService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(vw_ActiveCasesService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<vw_ActiveCases>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<vw_ActiveCases>(
      vw_ActiveCasesService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<vw_ActiveCases[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<vw_ActiveCases>(
      vw_ActiveCasesService.dataSourceName,
      options
    );
    return result;
  }
}
