/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface CaseNote {
  NoteId: string;
  CaseId: string;
  AuthorId: string;
  NoteCategory: string;
  Subject: string;
  Body: string;
  FollowUpFlag: boolean;
  FollowUpDate?: string;
  IsConfidential: boolean;
  CreatedOn: string;
  CreatedBy?: string;
  ModifiedOn?: string;
  ModifiedBy?: string;
}
