/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface CaseTask {
  TaskId: string;
  CaseId: string;
  Title: string;
  Description?: string;
  OwnerId: string;
  AssignedTo?: string;
  AssignedBy?: string;
  DueDate?: string;
  CompletedDate?: string;
  Status: string;
  Priority?: string;
  TaskType?: string;
  Type?: string;
  AutoGenerated: boolean;
  CreatedOn: string;
  CreatedBy?: string;
  ModifiedOn?: string;
  ModifiedBy?: string;
}
