/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export type GetActiveCasesRequest = Record<string, unknown>;

export interface GetActiveCasesResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: Record<string, unknown>;
}
