/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export type usp_CreateCaseRequest = Record<string, unknown>;

export interface usp_CreateCaseResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: Record<string, unknown>;
}
