/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface usp_UpdateCaseStatusRequest {
  ChangedBy?: string;
  NewStatus?: string;
  SystemCaseId?: string;
}

export interface usp_UpdateCaseStatusResponse {
  returncode?: number;
  outputparameters?: Record<string, unknown>;
  ResultSets?: {
    Table1?: {
      CaseId?: string;
      SystemCaseId?: string;
      CaseName?: string;
      EntryId?: number;
      EmployeeId?: string;
      EmployeeFirstName?: string;
      EmployeeLastName?: string;
      UnionGroupCode?: string;
      ViolationType?: string;
      Severity?: number;
      Likelihood?: number;
      Status?: string;
      Priority?: string;
      DOK?: string;
      IncidentDate?: string;
      ReportedDate?: string;
      InvestigatorId?: string;
      BaseCode?: string;
      RiskScore?: number;
      LitigationHold?: boolean;
      Description?: string;
      Summary?: string;
      InvestigationDeadline?: string;
      ClosureDeadline?: string;
      CloseoutScheduled?: boolean;
      EruCompleted?: boolean;
      Location?: string;
      ConcernType?: string;
      UrgencyLevel?: string;
      IsPrmCase?: boolean;
      FoiNeeded?: boolean;
      SubmitterId?: string;
      CreatedOn?: string;
      CreatedBy?: string;
      ModifiedOn?: string;
      ModifiedBy?: string;
    };
  };
}
