/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface vw_ActiveCases {
  CaseId: string;
  SystemCaseId: string;
  CaseName: string;
  Status: string;
  Priority?: string;
  DOK: string;
  IncidentDate: string;
  InvestigationDeadline?: string;
  ClosureDeadline?: string;
  RiskScore?: number;
  UrgencyLevel?: string;
}
